### ISSUE TITLE
CMIP6-PMIP4 request

### ISSUE THREAD

**Issue by CommonClimate** [pangeo-forge/cmip6-feedstock#10]
Hi,
@cisaacstern suggested that I post an issue here (blame him). 

For an NSF-funded project I am trying to obtain CMIP6-PMIP4 data for the past1000 or past2k runs (1000 or 1860y long at monthly resolution), extract surface temperature (`tas`), compute an appropriately weighted (`cos(lat)`) global mean, and export a data file (netCDF or other) with this for easy re-use and sharing. 

As a use case, consider [this simulation on the ESGF server](https://handle-esgf.dkrz.de/lp/21.14100/f68e78a0-0a51-35ba-a196-d8942318975c). Would I be able to make it ARCO by tweaking `recipe.py` and replacing line 500 with `CMIP6.PMIP.MPI-M.MPI-ESM1-2-LR.past2k.r1i1p1f1.Amon.tas.gn`, or does the script need further massaging? 

In case that makes a difference, the data are split between 93 files, each representing a 20-year period. 

Once I figure out this particular recipe, the idea would be to give a similar fate to other PMIP4 transient simulations. I am new to pangeo-forge, but eager to learn.

**Comment by jbusecke** [comment]
Ok that sounds good. Also there are not really docs for this particular repo at this point. Happy to have a chat once you have time to work on this!

**Comment by CommonClimate** [comment]
What is a good time to chat about this? I have time tomorrow or after July 4.

**Comment by CommonClimate** [comment]
Re: extra IDs, MPI ESM 1.2 is the only model to have archived results for the `past2k` experiment.  For `past1000`, both MIROC and MRI have done so:

- CMIP6.PMIP.MRI.MRI-ESM2-0.past1000.r1i1p1f1.Amon.tas.gn
- CMIP6.PMIP.MIROC.MIROC-ES2L.past1000.r1i1p1f2.Amon.tas.gn

**Comment by jbusecke** [comment]
We have managed to process your request in a new [PMIP specificic repo](https://github.com/pangeo-forge/CMIP6-PMIP-feedstock) and two of the three datasets are [online](https://pangeo-forge.org/dashboard/feedstock/79) and the third one is currently [running](https://pangeo-forge.org/dashboard/recipe-run/1104?feedstock_id=79). 
Please let me know if you can work with the data, and if all three datasets look ok we can close this issue.

**Comment by jbusecke** [comment]
🎉 the third one is done as well. 
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/14314623/192351265-6f21b4b9-adfb-47d5-8ae8-d57ab7e89f3b.png">

I will close this now, but please feel free to reopen when you have more requests or issues with the existing data.

**Comment by CommonClimate** [comment]
Thank you @jbusecke ! We'll give these a whirl and let you know.
