### ISSUE TITLE
Request for additional variables

### ISSUE THREAD

**Issue by MaxThomas90** [pangeo-forge/cmip6-feedstock#18]
Hello,

I would like to access several variables using intake that aren't currently available in the pangeo archive.

Specifically, I need variables:
sidmassth
sidmassgrowthwat
friver

For source_id=HadGEM3-GC31-LL, experiment_id=ssp585, table_id=SImon

Is it possible to get those brought accross into the pangeo archive?

Max

**Comment by jbusecke** [comment]
Hi @MaxThomas90, thanks for adding this request!

I found these instance_ids available from ESGF:

```
'CMIP6.ScenarioMIP.MOHC.HadGEM3-GC31-LL.ssp585.r3i1p1f3.SImon.sidmassth.gn.v20200504',
 'CMIP6.ScenarioMIP.MOHC.HadGEM3-GC31-LL.ssp585.r1i1p1f3.SImon.sidmassth.gn.v20200310',
 'CMIP6.ScenarioMIP.MOHC.HadGEM3-GC31-LL.ssp585.r3i1p1f3.SImon.sidmassgrowthwat.gn.v20200504',
 'CMIP6.ScenarioMIP.MOHC.HadGEM3-GC31-LL.ssp585.r1i1p1f3.SImon.sidmassgrowthwat.gn.v20200310'
```

`sidmassgrowthwat` is not available for that particular model as far as I can see. Would the datasets above still be of use?

**Comment by MaxThomas90** [comment]
Hi Julius,
Yes, I noticed those too.
Unfortunately the MOHC isn't useful to my current work.
I need experiment_id={ssp585, piControl, Historical}.
Is it possible to upload those? What sort of timeframe would I be looking
at?
Thanks,
Max

**Comment by jbusecke** [comment]
Hi Max, could you compile a full list of instance ids that you require ([this](https://github.com/jbusecke/pangeo-forge-esgf#parsing-a-list-of-instance-ids-using-wildcards) might be handy). 
It seems that this will be a rather moderate list of datasets, so uploading them will certainly be possible. Regarding the timeframe, I can unfortunately not make any promises. If everything goes smoothly this could be done in a few days, but we are still working out the kinks with pangeo-forge, so this might take quite a bit longer. I just want to be realistic here.

**Comment by jbusecke** [comment]
Apologies for the long wait here, but we have made significant progress on ingesting new stores via apache-beam at a larger scale recently. 
I am consolidating all the work in [cmip6-leap-feedstock](https://github.com/leap-stc/cmip6-leap-feedstock) and will archive this repo soon. 
If you are still interested in the requested data, please resubmit the request [here](https://github.com/leap-stc/cmip6-leap-feedstock/blob/main/README.md#how-can-i-request-new-data).
