### ISSUE TITLE
Request for missing variables 

### ISSUE THREAD

**Issue by rahulsivankutty** [pangeo-forge/cmip6-feedstock#20]
Hi,

We have been doing some ocean analysis from CMIP6 models and found that there are some random missing fields  in Pangeo cloud storage. Filling in those will help to complete the set of variables needed to do temperature and salinity budgets from around 20 models. 
Using  pangeo-forge-esgf tool, I could made a list of file ids which are available in ESGF, but not in cloud storage. Attaching the list. Can these data be uploaded into the cloud storage?
 
[missing_file_ids.txt](https://github.com/pangeo-forge/cmip6-feedstock/files/9972922/missing_file_ids.txt)

**Comment by jbusecke** [comment]
Apologies for the long wait here, but we have made significant progress on ingesting new stores via apache-beam at a larger scale recently. 
I am consolidating all the work in [cmip6-leap-feedstock](https://github.com/leap-stc/cmip6-leap-feedstock) and will archive this repo soon. 
If you are still interested in the requested data, please resubmit the request [here](https://github.com/leap-stc/cmip6-leap-feedstock/blob/main/README.md#how-can-i-request-new-data).
