### ISSUE TITLE
Missing Data

### ISSUE THREAD

**Issue by jonathantran800** [pangeo-forge/cmip6-feedstock#21]
Hi,

Can the CMIP6 data from this document could be added to the cloud please? If the request in the document needs to be a of a different form, we'd be glad to fix it.

Thank you,
Jonathan

[CMIP6_Pangeo_variable_listings_paragraphs.docx](https://github.com/pangeo-forge/cmip6-feedstock/files/10026151/CMIP6_Pangeo_variable_listings_paragraphs.docx)

**Comment by jbusecke** [comment]
Apologies for the long wait here, but we have made significant progress on ingesting new stores via apache-beam at a larger scale recently. 
I am consolidating all the work in [cmip6-leap-feedstock](https://github.com/leap-stc/cmip6-leap-feedstock) and will archive this repo soon. 
If you are still interested in the requested data, please resubmit the request [here](https://github.com/leap-stc/cmip6-leap-feedstock/blob/main/README.md#how-can-i-request-new-data).
