### ISSUE TITLE
Can you add sfcWind or UA, VA to the archive for all scenarios?

### ISSUE THREAD

**Issue by yucsong** [pangeo-forge/cmip6-feedstock#23]
Thanks

**Comment by jbusecke** [comment]
Could provide me with a list of instance ids as shown in the Readme [here](https://github.com/jbusecke/pangeo-forge-esgf)?

**Comment by jbusecke** [comment]
Apologies for the long wait here, but we have made significant progress on ingesting new stores via apache-beam at a larger scale recently. 
I am consolidating all the work in [cmip6-leap-feedstock](https://github.com/leap-stc/cmip6-leap-feedstock) and will archive this repo soon. 
If you are still interested in the requested data, please resubmit the request [here](https://github.com/leap-stc/cmip6-leap-feedstock/blob/main/README.md#how-can-i-request-new-data).
