### ISSUE TITLE
Requesting data to be added to the cloud

### ISSUE THREAD

**Issue by rebeccaherman1** [pangeo-forge/cmip6-feedstock#3]
I would love to have the following data added to the cloud, and I would prioritize it from most to least important as follows:
1. 'CMIP6.\*.\*.\*.hist-aer.\*.Amon.pr.\*.\*'
2. 'CMIP6.\*.\*.\*.[hist-aer, hist-nat].\*.Amon.ts.\*.\*'
3. 'CMIP6.\*.\*.\*.[hist-nat, hist-ghg].\*.Amon.pr.\*.\*'
4. 'CMIP6.\*.\*.\*.hist-ghg.\*.Amon.ts.\*.\*'
5. 'CMIP6.\*.\*.\*.piControl.\*.Amon.ts.\*.\*',
6. 'CMIP6.\*.\*.\*.piControl.\*.Amon.pr.\*.\*',
7. 'CMIP6.\*.\*.\*.piControl.\*.fx.sftlf.\*.\*’
8. 'CMIP6.\*.\*.\*.historical.\*.Amon.pr.\*.\*'
9. 'CMIP6.\*.\*.\*.historical.\*.Amon.ts.\*.\*'

Thank you!

**Comment by cisaacstern** [comment]
@jbusecke, now that #7 is merged, could you make a new PR adding a few representative instance ids for this request?

**Comment by jbusecke** [comment]
Hi @rebeccaherman1, I just wanted to check in here. Sorry that this took longer than expected. Do you still have use for the data? #11 implementes the first line in the request above, and Id be happy to try to add some more today.

**Comment by rebeccaherman1** [comment]
Thank you so much for working on it.
It may be a little too late for my second paper -- I had to submit the
revisions last Sunday.
But... if it comes back with more revisions, I could use the opportunity to
update the figures to include this data, and even if not, it could still
make it into my dissertation if it is completed in the next 2 or 3 weeks.
So yes, I'd say I still have use for it!
Thanks again,
Rebecca

**Comment by jbusecke** [comment]
Well I certainly do not hope for more revisions! Ill keep you posted here, and thanks again for inspiring a lot of this work.

**Comment by jbusecke** [comment]
Hi @rebeccaherman1, I could give this another go by tomorrow if this is still useful to you.
If that is not the case, or if this is only of use for the potential revisions, I would suggest to close this issue and reopen in case of major revisions?

**Comment by rebeccaherman1** [comment]
I will actually be resubmitting the paper to another journal shortly; how quickly would we know if it worked?
Rebecca

**Comment by jbusecke** [comment]
I just created a new feedstock and added the first request line (single member only for now) of datasets. You can check on the status [here](https://github.com/pangeo-forge/CMIP6-DAMIP-feedstock/deployments). 
Assuming that these pass, I can scale the number of datasets up relatively quickly (again, assuming that no problems arise).

**Comment by jbusecke** [comment]
Apologies for the long wait here, but we have made significant progress on ingesting new stores via apache-beam at a larger scale recently. 
I am consolidating all the work in [cmip6-leap-feedstock](https://github.com/leap-stc/cmip6-leap-feedstock) and will archive this repo soon. 
If you are still interested in the requested data, please resubmit the request [here](https://github.com/leap-stc/cmip6-leap-feedstock/blob/main/README.md#how-can-i-request-new-data).
