### ISSUE TITLE
CIL/Rhodium data requests

### ISSUE THREAD

**Issue by cisaacstern** [pangeo-forge/cmip6-feedstock#5]
Here's the list of requested instance ids from @rfofrich, initially provided in https://github.com/pangeo-data/pangeo-cmip6-cloud/issues/38#issuecomment-1103206197:

> https://gist.github.com/cisaacstern/847f86deaf763e3b4aa6cd062b09d99c

We'll start working on these as soon as the prototyped submission framework looks workable.

**Comment by rfofrich** [comment]
Sounds great! Our ideal timeline would be to have this completed within the month. However, I completely understand the limitations given you two may be spread thin between projects. Therefore, we do have a few workaround options if you feel that this timeline might be too ambitious.

**Comment by rfofrich** [comment]
@cisaacstern Thank you for the update. Our timeline is somewhat flexible. Therefore, no pressure if it takes slightly longer than expected and I'm looking forward to seeing this further developed. Thank you and @jbusecke again for working on this, it's extremely helpful.

**Comment by jbusecke** [comment]
I would get them directly from ESGF if everything works according to plan. So I should be good on that side. Ill keep you posted on the progress.

**Comment by jbusecke** [comment]
Apologies for the long wait here, but we have made significant progress on ingesting new stores via apache-beam at a larger scale recently. 
I am consolidating all the work in [cmip6-leap-feedstock](https://github.com/leap-stc/cmip6-leap-feedstock) and will archive this repo soon. 
If you are still interested in the requested data, please resubmit the request [here](https://github.com/leap-stc/cmip6-leap-feedstock/blob/main/README.md#how-can-i-request-new-data).
